In [119]:
from collections import deque

import gym
from gym import wrappers, logger

import random

import torch

In [9]:
env_name = 'CartPole-v1'

In [193]:
class Agent:
    def __init__(self, observation_size, action_space):
        self.mem = deque(maxlen=10000)
        self.action_space = action_space
        self.observation_size = observation_size
        print(action_space)
        layer_sizes = [
            self.observation_size,
            self.action_space.n
        ]

        self.W = []
        for i in range(len(layer_sizes) - 1):
            self.W.append(torch.ones(layer_sizes[i + 1], layer_sizes[i]).type(torch.FloatTensor))

    def choose_action(self, _observation, _reward, _done):
        return self.action_space.sample()

    def experience(self, _state, _action, _reward, _next_state, _done):
        self.mem.append((_state, _action, _reward, _next_state, _done))

    def minibatch(self, size=5):
        batch_s = min(size, len(self.mem))
        return random.sample(self.mem, batch_s)

    def qvalue(self, state):
        inp = torch.tensor(state.T).type(torch.FloatTensor)
        for w in self.W[:-1]:
            # inp = torch.cat((torch.Tensor([1.0]), inp))
            # inp = func(torch.mv(w, inp))
            inp = 1/(1 + torch.exp(-torch.mv(w, inp)))
        print(inp)
        print(self.W[-1])
        Y = torch.mv(self.W[-1], inp.double())
        print(Y)
        # e2 = (label.squeeze() - Y)
        # quad = e2.pow(2).sum()/2

INFO: Finished writing results. You can upload them to the scoreboard via gym.upload('/tmp/random-agent-results')


In [138]:
env.env.action_space

Discrete(2)

In [195]:
# You can set the level to logger.DEBUG or logger.WARN if you
# want to change the amount of output.
logger.set_level(logger.INFO)

env = gym.make(env_name)

# You provide the directory to write to (can be an existing
# directory, including one with existing data -- all monitor files
# will be namespaced). You can also dump to a tempdir if you'd
# like: tempfile.mkdtemp().
outdir = '/tmp/random-agent-results'
env = wrappers.Monitor(env, directory=outdir, force=True, video_callable=False)
env.seed(0)
observation_size = env.observation_space.shape[0]
action_size = env.action_space.n

agent = Agent(observation_size, env.action_space)

episode_count = 1000
reward = 0
done = False

rewards = []

INFO: Making new env: CartPole-v1
INFO: Clearing 2 monitor files from previous run (because force=True was provided)
Discrete(2)


In [196]:
for i in range(episode_count):
    ob = env.reset()
    rewardSum = 0
    steps = 0
    while not done:
        action = agent.choose_action(ob, reward, done)
        current_state = ob
        ob, reward, done, _ = env.step(action)
        rewardSum += reward
        steps += 1

        # Experience replay
        agent.experience(current_state, action, reward, ob, done)
        minibatch = agent.minibatch(size=10)
        print(current_state)
        agent.qvalue(current_state)

        if done:
            rewards.append(rewardSum)
            break
        # Note there's no env.render() here. But the environment still can open window and
        # render if asked by env.monitor: it calls env.render('rgb_array') to record video.
        # Video is not recorded every episode, see capped_cubic_video_schedule for details.

# Close the env and write monitor result info to disk
env.close()

[-0.04456399  0.04653909  0.01326909 -0.02099827]
tensor([-0.0446,  0.0465,  0.0133, -0.0210])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


RuntimeError: Expected object of scalar type Float but got scalar type Double for argument #2 'vec' in call to _th_mv